In [6]:
import os
import sys

import numpy as np
import matplotlib.pyplot as plt

sys.path.append('../')

from particle_filtering import particle_filtering_SIR
from environment_dynamics import RobotNavigationEnvSimple
from transition_kernels import RobotGaussianTransitionKernel
from observation_kernels import RobotGaussianLandmarkObservationKernel
from estimate_state import estimate_mean_variance_robot_location

%matplotlib inline

In [23]:
seed = 2

np.random.seed(seed)

landmarks = np.array([
    [-1, 2], 
    [5, 10], 
    [12, 14], 
    [18, 21], 
])

num_particles = 5000
num_iters = 8

resampling_method = "systematic"

initial_state = np.array([0., 0.])

init_particles_kwargs = {
    "x_range": np.array([0, 20]), 
    "y_range": np.array([0, 20]), 
    "hd_range": np.array([0, 2*np.pi]), 
}

sensor_obs_std = 0.1
init_env_kwargs = {
    "obs_std": sensor_obs_std, 
    "landmarks": landmarks, 
}

control_std = np.array([0.2, 0.05])
prediction_kwargs = {
    "u_std": control_std, 
}

transition_kernel_kwargs = {}

observation_kernel_kwargs = {
    "landmarks": landmarks, 
    "obs_std": sensor_obs_std, 
}

In [24]:
true_state_history, estimate_state_history, particle_history = particle_filtering_SIR(
    num_particles=num_particles, 
    num_iters=num_iters, 
    init_true_state=initial_state, 
    env_cls=RobotNavigationEnvSimple, 
    transition_kernel=RobotGaussianTransitionKernel, 
    observation_kernel=RobotGaussianLandmarkObservationKernel, 
    estimate_state_fn=estimate_mean_variance_robot_location, 
    save_particles=True, 
    resampling_method=resampling_method, 
    init_particles_kwargs=init_particles_kwargs, 
    init_env_kwargs=init_env_kwargs, 
    pred_kwargs=prediction_kwargs, 
    transition_kernel_kwargs=transition_kernel_kwargs, 
    observation_kernel_kwargs=observation_kernel_kwargs, 
)

In [25]:
true_state_history

[array([1., 1.]),
 array([2., 2.]),
 array([3., 3.]),
 array([4., 4.]),
 array([5., 5.]),
 array([6., 6.]),
 array([7., 7.]),
 array([8., 8.])]

In [26]:
estimate_state_history

[(array([0.98313286, 1.19990282]), array([4.97336165e-04, 5.96917689e-05])),
 (array([0.64241889, 2.79012105]), array([7.81408728e-07, 1.73092665e-04])),
 (array([0.89959891, 4.34954454]), array([3.30634961e-06, 6.29833939e-05])),
 (array([1.16932335, 5.91646807]), array([1.18085787e-06, 3.60414827e-05])),
 (array([1.20360594, 7.51855607]), array([3.77781552e-07, 3.55223867e-05])),
 (array([1.51456118, 9.09593529]), array([2.78362124e-07, 1.20636518e-05])),
 (array([ 1.65301474, 10.66912919]), array([2.13076069e-07, 2.75232024e-05])),
 (array([ 1.81714106, 12.23505554]), array([4.13827568e-07, 3.70563056e-05]))]